/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api;

import com.telstra.api.controllers.*;
import com.telstra.api.http.client.HttpClient;

public class AazarKhanTelstraSMSAPIClient {
    /**
     * Singleton access to Client controller
     * @return	Returns the APIController instance 
     */
    public APIController getClient() {
        return APIController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public AazarKhanTelstraSMSAPIClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public AazarKhanTelstraSMSAPIClient(String oAuthAccessToken) {
        this();
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}