/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;

public class AuthenticationResponseBuilder {
    //the instance to build
    private AuthenticationResponse authenticationResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AuthenticationResponseBuilder() {
        authenticationResponse = new AuthenticationResponse();
    }

    /**
     * The access token generated after authentication is checked
     */
    public AuthenticationResponseBuilder accessToken(String accessToken) {
        authenticationResponse.setAccessToken(accessToken);
        return this;
    }

    /**
     * 1 hour till token expires
     */
    public AuthenticationResponseBuilder expiresIn(double expiresIn) {
        authenticationResponse.setExpiresIn(expiresIn);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AuthenticationResponse build() {
        return authenticationResponse;
    }
}