/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AuthenticationResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5168664105349392617L;
    private String accessToken;
    private double expiresIn;
    /** GETTER
     * The access token generated after authentication is checked
     */
    @JsonGetter("access_token")
    public String getAccessToken ( ) { 
        return this.accessToken;
    }
    
    /** SETTER
     * The access token generated after authentication is checked
     */
    @JsonSetter("access_token")
    public void setAccessToken (String value) { 
        this.accessToken = value;
    }
 
    /** GETTER
     * 1 hour till token expires
     */
    @JsonGetter("expires_in")
    public double getExpiresIn ( ) { 
        return this.expiresIn;
    }
    
    /** SETTER
     * 1 hour till token expires
     */
    @JsonSetter("expires_in")
    public void setExpiresIn (double value) { 
        this.expiresIn = value;
    }
 
}
 