/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;

public class GetMessageResponseBuilder {
    //the instance to build
    private GetMessageResponse getMessageResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetMessageResponseBuilder() {
        getMessageResponse = new GetMessageResponse();
    }

    /**
     * Where the SMS is coming from
     */
    public GetMessageResponseBuilder from(String from) {
        getMessageResponse.setFrom(from);
        return this;
    }

    /**
     * When the SMS was received
     */
    public GetMessageResponseBuilder acknowledgedTimestamp(String acknowledgedTimestamp) {
        getMessageResponse.setAcknowledgedTimestamp(acknowledgedTimestamp);
        return this;
    }

    /**
     * The body or content of SMS
     */
    public GetMessageResponseBuilder content(String content) {
        getMessageResponse.setContent(content);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetMessageResponse build() {
        return getMessageResponse;
    }
}