/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetMessageResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5010256650086225668L;
    private String from;
    private String acknowledgedTimestamp;
    private String content;
    /** GETTER
     * Where the SMS is coming from
     */
    @JsonGetter("from")
    public String getFrom ( ) { 
        return this.from;
    }
    
    /** SETTER
     * Where the SMS is coming from
     */
    @JsonSetter("from")
    public void setFrom (String value) { 
        this.from = value;
    }
 
    /** GETTER
     * When the SMS was received
     */
    @JsonGetter("acknowledgedTimestamp")
    public String getAcknowledgedTimestamp ( ) { 
        return this.acknowledgedTimestamp;
    }
    
    /** SETTER
     * When the SMS was received
     */
    @JsonSetter("acknowledgedTimestamp")
    public void setAcknowledgedTimestamp (String value) { 
        this.acknowledgedTimestamp = value;
    }
 
    /** GETTER
     * The body or content of SMS
     */
    @JsonGetter("content")
    public String getContent ( ) { 
        return this.content;
    }
    
    /** SETTER
     * The body or content of SMS
     */
    @JsonSetter("content")
    public void setContent (String value) { 
        this.content = value;
    }
 
}
 