/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetMessageStatusResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4871754890228446427L;
    private String to;
    private String receivedTimestamp;
    private String sentTimestamp;
    private String status;
    /** GETTER
     * Where the SMS is being sent
     */
    @JsonGetter("to")
    public String getTo ( ) { 
        return this.to;
    }
    
    /** SETTER
     * Where the SMS is being sent
     */
    @JsonSetter("to")
    public void setTo (String value) { 
        this.to = value;
    }
 
    /** GETTER
     * When the SMS was received
     */
    @JsonGetter("receivedTimestamp")
    public String getReceivedTimestamp ( ) { 
        return this.receivedTimestamp;
    }
    
    /** SETTER
     * When the SMS was received
     */
    @JsonSetter("receivedTimestamp")
    public void setReceivedTimestamp (String value) { 
        this.receivedTimestamp = value;
    }
 
    /** GETTER
     * When the SMS was sent
     */
    @JsonGetter("sentTimestamp")
    public String getSentTimestamp ( ) { 
        return this.sentTimestamp;
    }
    
    /** SETTER
     * When the SMS was sent
     */
    @JsonSetter("sentTimestamp")
    public void setSentTimestamp (String value) { 
        this.sentTimestamp = value;
    }
 
    /** GETTER
     * Shows the response status
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Shows the response status
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
}
 