/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendSMSToBodyObject 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4897664674795027747L;
    private String to;
    private String body;
    /** GETTER
     * Where the SMS is being sent
     */
    @JsonGetter("to")
    public String getTo ( ) { 
        return this.to;
    }
    
    /** SETTER
     * Where the SMS is being sent
     */
    @JsonSetter("to")
    public void setTo (String value) { 
        this.to = value;
    }
 
    /** GETTER
     * Content of the SMS
     */
    @JsonGetter("body")
    public String getBody ( ) { 
        return this.body;
    }
    
    /** SETTER
     * Content of the SMS
     */
    @JsonSetter("body")
    public void setBody (String value) { 
        this.body = value;
    }
 
}
 