/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendSMSResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5409593356458577909L;
    private String messageId;
    /** GETTER
     * The message id received when SMS is sent
     */
    @JsonGetter("messageId")
    public String getMessageId ( ) { 
        return this.messageId;
    }
    
    /** SETTER
     * The message id received when SMS is sent
     */
    @JsonSetter("messageId")
    public void setMessageId (String value) { 
        this.messageId = value;
    }
 
}
 