/*
 * AazarKhanTelstraSMSAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.api.models;

import java.util.*;

public class SendSMSToBodyObjectBuilder {
    //the instance to build
    private SendSMSToBodyObject sendSMSToBodyObject;

    /**
     * Default constructor to initialize the instance
     */
    public SendSMSToBodyObjectBuilder() {
        sendSMSToBodyObject = new SendSMSToBodyObject();
    }

    /**
     * Where the SMS is being sent
     */
    public SendSMSToBodyObjectBuilder to(String to) {
        sendSMSToBodyObject.setTo(to);
        return this;
    }

    /**
     * Content of the SMS
     */
    public SendSMSToBodyObjectBuilder body(String body) {
        sendSMSToBodyObject.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SendSMSToBodyObject build() {
        return sendSMSToBodyObject;
    }
}